### PR TITLE
Nav. Bar is fixed in all subpages of development and fixed dark mode

### PR DESCRIPTION
**Pull request by Anubhavgupta14**
Nav. Bar is fixed in all subpages of development and fixed dark mode.
Before
A
After
G1
Before
B
After
G2
@myhacktech @tier3guy Kindly Review it.
Issue Solved :- #165

### CODE REVIEW

**Comment by myhacktech** [comment]
lgtm @tier3guy

**Comment by tier3guy** [comment]
Please resolve the conflicts in order to be get merged.

**Comment by Anubhavgupta14** [comment]
@tier3guy Sure, I will resolve Conflicts soon.

**Comment by Anubhavgupta14** [comment]
@tier3guy Kindly merge it, Now All the conflicts has been resolved.

**Pull request merged**
