### PR TITLE
background changes

### PR DESCRIPTION
**Pull request by ArunaAT**
acadmia2

acadmia4

### CODE REVIEW

**Comment by narayan954** [comment]
Please elaborate the changes you made and issue you've resolved.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by ArunaAT** [comment]
I changed the background color of the dark mode and removed the button's background color from both dark and light mode and add border to the button.

**Comment by narayan954** [comment]
issue ss)

Clicking once on accordion makes it dull , also , some new changes are not reflecting with this pr along with a merge conflict. 
Can you look into this?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by ArunaAT** [comment]
Yes I will look into it, currently I am out of town, after 2 days I will be back and i will start right away.

**Comment by narayan954** [comment]
okay @ArunaAT ,also, please solve the merge conflicts .

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Pull request merged**
