### PR TITLE
Fixed nav bar in interview page & footers. Closes #70 and #66

### LINKED ISSUE #70: Navbar is not visible in - interview prep page
URL - https://acadmica.social/src/pages/interviewPrep/main.html

also in the responsive navbar - add github and subscribe us button

### PR DESCRIPTION
**Pull request by SushanthReddy-49**

### CODE REVIEW

**Comment by SushanthReddy-49** [comment]
Hey @tier3guy fixed the NavBar and Footer.

**Comment by tier3guy** [comment]
Can you share the screenshots !!

**Comment by SushanthReddy-49** [comment]
image
image

**Comment by SushanthReddy-49** [comment]
Here are the Screenshots @tier3guy

**Comment by tier3guy** [comment]
Great work

**Pull request merged**
