### PR TITLE
added 404 page

### PR DESCRIPTION
**Pull request by losier**
Hey, @tier3guy here is my contribution to your project hope you like it.
Please let me know if you want some more changes too.

### CODE REVIEW

**Comment by tier3guy** [comment]
Hey @losier Can you send one SS?

**Comment by tier3guy** [comment]
Hey @losier I checked the page, its too fancy, can you make it minimal. 

> Maintain the theme of the org. (Blue & white)

**Comment by losier** [comment]
[Image](https://ibb.co/yNB23xH)

**Comment by tier3guy** [comment]
@losier Are you ssoc participant ? if yes share you mail / discord Id.
Issue : #16

**Pull request merged**
