### PR TITLE
Fixed typos and grammatical mistakes in README.md

### PR DESCRIPTION
**Pull request by prjailani**
Hi Sir/Madam,
    Fixed typos and grammatical mistakes in README.md. Thanks.

### CODE REVIEW

**Comment by narayan954** [comment]
Can you mention the issue you've resolved ?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by prjailani** [comment]
> Thanks but can you mention the issue you've resolved ?
> 
> __
> [sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable
> 

I didn't created an issue. Is it necessary, sir?

**Comment by narayan954** [comment]
Yes, the proper way to contribute to most open source projects is , raise an issue, get yourself assigned to the issue and then raise a PR solving that issue.
Thank you. 
You can quickly create this issue and mention it in this PR , I'll be happy to consider it asap :)

**Comment by prjailani** [comment]
> Yes, the proper way to contribute to most open source projects is , raise an issue, get yourself assigned to the issue and then raise a PR solving that issue.
> Thank you. 
> You can quickly create this issue and mention it in this PR , I'll be happy to consider it asap :)
> 
> 

Created issue sir. Anything else need to be done?

**Comment by narayan954** [comment]
Thanks for your contribution @prjailani .
Fixed issue #162

**Comment by prjailani** [comment]
> Thanks for your contribution @prjailani .
> Fixed issue #162 
> 
> 

Thanks for merging. This is my first contribution for this project BTW.

**Comment by narayan954** [comment]
woah congratulations !! @prjailani  keep contributing !

**Pull request merged**
