### PR TITLE
Handled the responsiveness of Image

### PR DESCRIPTION
**Pull request by ganesh-utla**

### CODE REVIEW

**Comment by ganesh-utla** [comment]
image
image
Issue fixed!

**Review by narayan954 — APPROVED** [review]

**Comment by narayan954** [comment]
Thank you for contributing! :)

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by ganesh-utla** [comment]
Hey! @narayan954 Thanks for that!! But now I'm unable to find the another issues left and issue was taken if I found any. So how to find any issues? Can you suggest any.

**Comment by narayan954** [comment]
@ganesh-utla you can check for inactive issues and comment to confirm that and also in some cases multiple issues are assigned to same person who'll be willing to share/give you up their assigned issues.

**Comment by narayan954** [comment]
issue #135  was closed without resolution , you may even open it again and try to solve it.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by ganesh-utla** [comment]
Okay! Thank you!!

**Pull request merged**
