### PR TITLE
Feat/added theme switcher

### PR DESCRIPTION
**Pull request by vaibhavsharma1234**
i have added theme switcher on the main page 
themeswitcher2
themeswitcher1
themeswitcher3
these are therefrence images

### CODE REVIEW

**Comment by Divesh2003** [comment]
My suggestion is to change the theme using a small logo of a dark and light theme. May you understand the thing.

**Comment by vaibhavsharma1234** [comment]
Ok understood will try to implement it

**Comment by vaibhavsharma1234** [comment]
icon-theme
now is it ok ?

**Comment by tier3guy** [comment]
Updates Needed: 
- By default the theme should be in light mode.
- In the Dark Mode, fix hover effect in the discord button. (make the discord icon dark on hover)
- In mobile, remove the curve edges in the nav in the light mode.
- In mobile, align the hamburger icon to the right.

**Comment by tier3guy** [comment]
Also I had reverted few changes, please update your local code with the remote before making any PR.

**Comment by vaibhavsharma1234** [comment]
i will make by default light 
discord button hover will also be done
curve edges u mean on icon of dark-light switcher
aligining i will see what i can do
ok scroll bar background will be dark

**Comment by vaibhavsharma1234** [comment]
i will make a pr again after these changes

**Comment by tier3guy** [comment]
> i will make a pr again after these changes

please update your local code.

**Comment by tier3guy** [comment]
> 

Curve edges means in the navbar see its edges in the mobile view.

**Comment by tier3guy** [comment]
@dilpreet102 Please add the theme switcher.

**Comment by vaibhavsharma1234** [comment]
What u want me do 
I am confused
U want me to do changes that u suggested and apply theme switcher to all page 
Or update my local code and don't make any changes
Kindly make it clear

**Comment by narayan954** [comment]
@vaibhavsharma1234 just do the changes as suggested and apply theme switcher .No need of confusion.

**Pull request merged**
