### PR TITLE
new commit improved responsiveness

### PR DESCRIPTION
**Pull request by vaibhavsharma1234**

### CODE REVIEW

**Review by myhacktech — COMMENTED** [review]
@tier3guy please check if any else thing to be done here

**Review by myhacktech — APPROVED** [review]

**Review by tier3guy — APPROVED** [review]

**Comment by tier3guy** [comment]
@vaibhavsharma1234 Can you share the ss of the changes.

**Comment by vaibhavsharma1234** [comment]
acad1
acad2
acad3
here are the pics

**Comment by tier3guy** [comment]
@Divesh2003 @myhacktech @vaibhavsharma1234 
What was issue no. ?? Can uh guys verify it ?

**Comment by vaibhavsharma1234** [comment]
Screenshot_2022-08-07-18-52-04-981_com android chrome
Is there any problem?

**Pull request merged**
