### PR TITLE
Fixed issue#177 with the buy me a coffee logo

### PR DESCRIPTION
**Pull request by fykaa**
Issue - https://github.com/tier3guy/Acadmica/issues/177

Before image
After image

### CODE REVIEW

**Comment by myhacktech** [comment]
LGTM @tier3guy

**Comment by narayan954** [comment]
Hey @fykaa  can you please resolve the conflicts

**Comment by tier3guy** [comment]
Please resolve all the conflicts.

**Comment by fykaa** [comment]
Hi @narayan954 , would you check once

**Pull request merged**
