### PR TITLE
add hover for icons

### PR DESCRIPTION
**Pull request by Trevy05**
This is a pull request for issue #8 Icon colors.

Hello again. I navigated to the src/CSS/academics/main.css file.
I added hover effects for each of the icons that didn't previously have them.

icon-pr
icon-pr2
icon-pr3
icon-pr4

### CODE REVIEW

**Comment by tier3guy** [comment]
You did an amazing work @Trevy05 !! Kudos to you.
Waiting for your further contributions.

**Comment by tier3guy** [comment]
@Trevy05 Are you SSOC participant ?
Issue : #8

**Comment by Trevy05** [comment]
I don't even know what that is exactly.

**Comment by tier3guy** [comment]
> I don't even know what that is exactly.

Cool cool 😄😄, no issues. Willing to have more contributions from your side.

**Comment by Trevy05** [comment]
Do you mind explaining it to me, googling it isn't very helpful?

**Comment by tier3guy** [comment]
@Trevy05  Actually in India, we are running an open source program SSOC (Social Summer of Code) to motivate beginners in Open Source. That's why I was asking if you were an SSOC participant, so that I will allot you the points for making the PR.

**Pull request merged**
