### PR TITLE
Aritra pr

### PR DESCRIPTION
**Pull request by thecodermaniac**
color bug of accordian in dark and day mode fixed

image
image

image placement fixed in mobile view

image

text color fixed

image

nav bar fixed

### CODE REVIEW

**Review by narayan954 — CHANGES_REQUESTED** [review]
can you please resolve the merge conflicts?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by thecodermaniac** [comment]
> can you please resolve the merge conflicts?
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix  |  **Tags:** Not reusable

**Review by thecodermaniac — COMMENTED** [review]
its working

**Review by narayan954 — APPROVED** [review]

**Comment by narayan954** [comment]
Looks good, Thanks for your contribution!

**Pull request merged**
