### PR TITLE
Updated the Discord Server Link

### PR DESCRIPTION
**Pull request by rohangupta8756**

### CODE REVIEW

**Comment by tier3guy** [comment]
@rohangupta8756 are you ssoc participant ?

**Comment by rohangupta8756** [comment]
> @rohangupta8756 are you ssoc participant ?

Yes @tier3guy

**Comment by tier3guy** [comment]
@rohangupta8756  please share your mail ID I am unable to find your name in my list !!

**Comment by rohangupta8756** [comment]
@tier3guy 
Email-ID :    rohangupta8756@gmail.com

**Pull request merged**
