### PR TITLE
Closes #51, #53, #55 and #56 with few minor changes.

### LINKED ISSUE #51: Loading Screen
Build one loading screen and make it last for around 2-3 seconds

### PR DESCRIPTION
**Pull request by SushanthReddy-49**
Hi, I took some liberty and made few changes to the Content in the page and scrollbar width.

### CODE REVIEW

**Comment by SushanthReddy-49** [comment]
Hi @tier3guy , Can you review this and merge the PR.

**Comment by tier3guy** [comment]
All the prs will get merge after 1st August

**Comment by SushanthReddy-49** [comment]
@tier3guy Ok Cool.

**Comment by tier3guy** [comment]
@SushanthReddy-49 Are you a SSOC participant ?? if yes please share your mail id here !!

**Pull request merged**
